### ISSUE TITLE
most of the scripts not working on 3.9.7

### ISSUE THREAD

**Issue by lawlerboy1** [BakingBrains/Hand_Tracking-_Using_OpenCV#1]
Traceback (most recent call last):
  File "C:\Users\Username\Me\Filepath\file.py", line 6, in <module>
    detector = htm.handDetector(detectionCon=0.7)
  File "C:\Users\Username\Me\Filepath\file.py", line 20, in __init__
    self.hands = self.mpHands.Hands(self.mode, self.maxHands, self.detectionCon, self.trackCon)
  File "C:\Users\Username\Me\Filepath\file.py", line 114, in __init__
    super().__init__(
  File "C:\Users\Username\Me\Filepath\file.py", line 258, in __init__
    self._input_side_packets = {
  File "C:\Users\Username\Me\Filepath\file.py", line 259, in <dictcomp>
    name: self._make_packet(self._side_input_type_info[name], data)
  File "C:\Users\Username\Me\Filepath\file.py", line 513, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(data)
TypeError: create_int(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int) -> mediapipe.python._framework_bindings.packet.Packet

Invoked with: 0.7

this happened as soon as the hand detector function was used

**Comment by BakingBrains** [comment]
@lawlerboy1
try:
pip install mediapipe==0.8.7
pip install opencv_python==4.5.5.64

**Comment by BakingBrains** [comment]
If you are facing any issues, please reopen.
